### ISSUE TITLE
Failed to load the widgetset on the demo site.

### ISSUE THREAD

**Issue by guadaran** [miguelperezcolom/mateu-mdd#2]
Hi there,

The following error appears when entering to the demo site: http://mdddemo.mateu.io

`Failed to load the widgetset: ./VAADIN/widgetsets/com.vaadin.DefaultWidgetSet/com.vaadin.DefaultWidgetSet.nocache.js?1542127342046
`

**Browser:** Safari 11.1.2 and Vivaldi 2.2.1360.4
**OS:** OSX

Thank you.

**Comment by miguelperezcolom** [comment]
Hi Guadaran,

thanks for the info and sorry for the delay. I have not seen your issue till now.

Yes. I think it is something related to jetty + vaadin as it seems this happens when, for some reason, jetty is detecting that something has changed in the webapp and it reloads the context. From that moment, the vaadin servlet stops working. 

I have one customer working with a mateu-mdd based application in production and it has been working for months without problem but, for the demo, this issue is happening approx. every 2 weeks. 

This is something I must look at ;)

I have restarted jetty and now it's up again.


Best regards,

Miguel

**Comment by guadaran** [comment]
Hi @miguelperezcolom 

Thanks for solving this!

Regards.
